name: Add New Terraform Casks
on:
  schedule:
    # Daily at 04:20 UTC
    - cron:  '20 4 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  add_new_casks:
    name: Add New Terraform Casks
    # Only run on the main repo
    if: github.repository == 'tmatilai/homebrew-terraforms'
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Find and add new Casks
        shell: bash
        run: |
          echo 'TF_VERSIONS<<EOF' >> $GITHUB_ENV
          ./scripts/add_new_terraform_casks | while read version path; do
            echo "Adding v$version"
            printf '* [v%s](https://github.com/hashicorp/terraform/releases/tag/v%s)\n' "$version" "$version" >> $GITHUB_ENV

            git add "$path"
            git commit -m "Add Terraform v$version"
          done
          echo 'EOF' >> $GITHUB_ENV

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: new-terraform-versions
          title: Add new Terraform versions
          body: |
            **Versions:**

            ${{ env.TF_VERSIONS }}

            Generated by "${{ github.workflow }}" GitHub Action
          delete-branch: true
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

      - name: Enable auto-merge
        if: steps.create-pr.outputs.pull-request-number
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --auto --squash
